spring.application.name: borrowing-power-p  rediction-service

management:
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APPLICATION_KEY}
        host-tag: ${spring.application.name}.voicestreams.com
        step: 5s
